name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */10 * * *'  # Uruchamia się co 10 godzin
  workflow_dispatch:  # Umożliwia ręczne uruchomienie workflow do testowania

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create empty commit
        run: |
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            git commit --allow-empty -m "Empty commit to keep Streamlit app active"
            git push 